/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2017-02-19 14:13:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>ITCS 3162 - Group H2</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/scrollingnav.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-fixed-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header page-scroll\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\".navbar-ex1-collapse\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand page-scroll\" href=\"#page-top\">Housing\r\n");
      out.write("\t\t\t\t\tPrice Estimator</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<!-- Hidden li included to remove active class from about link when scrolled up past about section -->\r\n");
      out.write("\t\t\t\t\t<li class=\"hidden\"><a class=\"page-scroll\" href=\"#page-top\"></a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Intro Section -->\r\n");
      out.write("\t<section id=\"intro\" class=\"intro-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<h1>Estimate Housing Prices!</h1>\r\n");
      out.write("\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t<strong>Usage Instructions:</strong> To estimate a price, enter\r\n");
      out.write("\t\t\t\t\t\tthe corresponding inputs and click the Run Analysis button!\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary page-scroll\" href=\"#estimateSection\">Start\r\n");
      out.write("\t\t\t\t\t\tEstimating!</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- About Section -->\r\n");
      out.write("\t<section id=\"estimateSection\" class=\"about-section\">\r\n");
      out.write("\t\t<!--     \t<img src=\"img/ajax-loader.gif\" id=\"ajaxImg\" /> -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t\t<h1 class='page-header'>Estimate Price</h1>\r\n");
      out.write("\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"address\">Street Address: </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"address\" placeholder=\"Enter address...\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"city\">City: </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"city\" placeholder=\"Enter city...\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"state\">State: </label> <select id=\"state\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AL\">Alabama</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AK\">Alaska</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AZ\">Arizona</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AR\">Arkansas</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"CA\">California</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"CO\">Colorado</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"CT\">Connecticut</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"DE\">Delaware</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"DC\">District Of Columbia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"FL\">Florida</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"GA\">Georgia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"HI\">Hawaii</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"ID\">Idaho</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"IL\">Illinois</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"IN\">Indiana</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"IA\">Iowa</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"KS\">Kansas</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"KY\">Kentucky</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"LA\">Louisiana</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"ME\">Maine</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MD\">Maryland</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MA\">Massachusetts</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MI\">Michigan</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MN\">Minnesota</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MS\">Mississippi</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MO\">Missouri</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MT\">Montana</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NE\">Nebraska</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NV\">Nevada</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NH\">New Hampshire</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NJ\">New Jersey</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NM\">New Mexico</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NY\">New York</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"NC\">North Carolina</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"ND\">North Dakota</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"OH\">Ohio</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"OK\">Oklahoma</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"OR\">Oregon</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PA\">Pennsylvania</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RI\">Rhode Island</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SC\">South Carolina</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SD\">South Dakota</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"TN\">Tennessee</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"TX\">Texas</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"UT\">Utah</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"VT\">Vermont</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"VA\">Virginia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"WA\">Washington</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"WV\">West Virginia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"WI\">Wisconsin</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"WY\">Wyoming</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<button id='submitBtn' type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#loadingId\">Run Analysis</button>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<h4><span id='warnLabel' class=\"label label-default\" style=\"display:none;\">Please enter an address, city, and state!</span></h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t<h3>Your Estimated Value</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-info\" id='alertInfo'>\r\n");
      out.write("\t\t\t\t\t\t<h2>???</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-success\" id='estimatePrice'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"display: none;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section id='factsInfo' class='services-section' style=\"display: none;\">\r\n");
      out.write("\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\t\t\t<h1 class='page-header'>Other Facts</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-6\" class=\"well\">\r\n");
      out.write("\t\t\t<h3>Value Over Time</h3>\r\n");
      out.write("\t\t\t<div id=\"estimateChart\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-6\" class=\"well\">\r\n");
      out.write("\t\t\t<h3>Neighborhood Statistics</h3>\r\n");
      out.write("\t\t\t<div id=\"areaStats\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"loadingId\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"loadingIndicator\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-spinner fa-spin\" style=\"font-size: 150px;\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"js/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scrolling Nav JavaScript -->\r\n");
      out.write("\t<script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/scrolling-nav.js\"></script>\r\n");
      out.write("\t<script src=\"js/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
